config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :stores, only: [:show, :index] do
    member do
      post 'bookmark' => 'bookmarks#create'
      delete 'bookmark' => 'bookmarks#destroy'
    end
  end
  resources :users do
    member do
      get :bookmarks
    end
  end
  resources :lists, only: [:create, :destroy]
  resources :reviews, only: [:create, :destroy]
  get    'signup'      =>  'users#new'
  post   'signup'      =>  'users#create'
  get    'login'       =>  'sessions#new'
  post   'login'       =>  'sessions#create'
  delete 'logout'      =>  'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/views/static_pages/home.html.erb
<% content_for(:html_title) { 'Supamemo' } %>
<div class="topPage">
  <section class="topHeroSection">
    <div class="topHero__wrap">
      <div class="container">
        <div class="topHero__flexBox">
          <h1 class="topHero__title">日々の<br>お買い物を<br>安く</h1>
        </div>
      </div>
    </div>
  </section>
  <section class="serviceSection stSection">
    <div class="container">
      <h2 class="stSectionTitle">簡単3step</h2>
      <div class="serviceColumn">
        <div class="serviceCardWrap">
          <div class="cardWrap">
            <div class="serviceCardBox cardBox">
              <div class="row">
                  <div class="col-xs-12 col-sm-6 col-md-4 back-white">
                    <div class="step">
                      <i class="fa fa-store-alt fa-3x"></i>
                      <div class="service__title">探す</div>
                      <div class="service__description">
                      まずは<br>家の近くのスーパーを見つけよう。
                      </div>
                    </div>
                  </div>
                  <div class="col-xs-12 col-sm-6 col-md-4 back-white">
                    <div class="step">
                      <i class="fa fa-edit fa-3x"></i>
                      <div class="service__title">メモする</div>
                      <div class="service__description">
                      その日買ったものを<br>記録しよう。
                      </div>                    
                    </div>
                  </div>
                  <div class="col-xs-12 col-sm-6 col-md-4 back-white">
                    <div class="step">
                      <i class="fa fa-fish fa-3x"></i>
                      <div class="service__title">比較する</div>
                      <div class="service__description">
                      今日買いたい食品は<br>どこのスーパーが一番安い？
                      </div>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="searchSection stSection">
    <div class="container">
      <h2 class="stSectionTitle">
        <a name="search-super" class="atag">スーパーを探す</a>
      </h2>
      <div class="search__image">
        <i class="fa fa-map-marker-alt fa-5x"></i>
      </div>
      <div class="search-nowplace">
        <button id="getPlace" class="btn btn_color">現在地から探す</button>
      </div>
      <div class="search-text">
       <p class="search-text-title">キーワードから探す</p>
        <%= form_tag(stores_path,:method => 'get') do %>
          <%= text_field_tag :search, params[:search], :class =>'textbox', :placeholder =>"例(吉祥寺駅/武蔵野市吉祥寺南町etc..)" %>
        <% end %>
      </div>
      <p>(どちらも半径500m圏内で検索されます)</p>
    </div>
  </section>
</div>