config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :stores, only: [:show, :index] do
    member do
      post 'bookmark' => 'bookmarks#create'
      delete 'bookmark' => 'bookmarks#destroy'
    end
  end
  resources :users do
    member do
      get :bookmarks
    end
  end
  resources :lists, only: [:create, :destroy]
  resources :reviews, only: [:create, :destroy]
  get    'signup'      =>  'users#new'
  post   'signup'      =>  'users#create'
  get    'login'       =>  'sessions#new'
  post   'login'       =>  'sessions#create'
  delete 'logout'      =>  'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/stores_controller.rb
# require 'net/http'
# require 'uri'
# require 'json'
class StoresController < ApplicationController
  def index
    if params[:place]
      place = params[:place]
    elsif params[:search]
      results = Geocoder.search(params[:search])
      if results.present?
        lat = results.first.latitude
        lon = results.first.longitude
        place = "#{lat},#{lon}"
      end
    end

    url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?'
    client = HTTPClient.new
    query = {
      language: 'ja',
      location: "#{place}",
      radius: 500,
      types: 'grocery_or_supermarket',
      key: ENV['API_KEY'],
    }
    request = client.get(url, query)
    hairetu = JSON.parse(request.body)
    @super = hairetu['results']
  end

  def show
    @name = params[:id]

    nihongo = "https://maps.googleapis.com/maps/api/place/textsearch/json?query=#{@name}"
    enc_str = URI.encode nihongo
    client = HTTPClient.new
    q = {
      key: ENV['API_KEY'],
      language: 'ja',
    }
    request = client.get(enc_str, q)
    hairetu = JSON.parse(request.body)
    @super = hairetu['results'].first
    sort = params[:sort] || "created_at DESC"
    @list = List.new
    @lists = List.where(store_name: @name).order(sort).defo(params[:page])
    @reviews = Review.where(store_name: @name).latest_order.defo(params[:page])
    @review = Review.new
  end
end

app/views/stores/_add_lists.html.erb
<button type="button" class="btn_add_list" data-toggle="modal" data-target="#post">
<i class="fa fa-plus-circle"></i>この店の買い物リストを追加する</button>
<div class="modal fade" id="post" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog wid" role="document">
    <div class="modal-content">
      <%= form_with(model: list, local: true) do |f| %>
        <div class="modal-body pd15170">
          <ul class="modal-ul">
            <li>
              <%= f.label :product, '商品' %>
              <%= f.text_field :product %>
            </li>
            <li>
              <%= f.label :price, '金額' %>
              <%= f.text_field :price %>円              
            </li>
            <li>
              <%= f.label :amount, '数量' %>
              <%= f.text_field :amount %>
              <%= f.select :unit, [["個入り", "個入り"], ["本", "本"], ["パック", "パック"], ["袋", "袋"],["g(当り)", "g(当り)"],["切", "切"]], include_blank: "選択" %>
            </li>
          </ul>
        </div>
        <div class="modal-footer textcenter">
          <button type="button" class="btn circle-btn pl-10" data-dismiss="modal">閉じる</button>
          <%= f.submit "追加", class: "btn circle-btn" %>
          <%= f.hidden_field :store_name, :value => name %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/stores/_add_review.html.erb
<button type="button" class="shop-review-btn" data-toggle="modal" data-target="#post2">
このお店の口コミを投稿</button>
<div class="modal fade" id="post2" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog wid" role="document">
    <div class="modal-content">
      <%= form_with(model: review, local: true) do |f| %>
        <div class="modal-body">
          <ul class="modal-ul">
            <li>
              <%= f.label :content, 'コメント' %>
              <%= f.text_area :content, size: "70x5", class: "resizenone" %>
            </li>
          </ul>
        </div>
        <div class="modal-footer textcenter">
          <button type="button" class="btn circle-btn-o pl-10" data-dismiss="modal">閉じる</button>
          <%= f.submit "投稿", class: "btn circle-btn-o" %>
          <%= f.hidden_field :store_name, :value => name %>
        </div>
      <% end %>  
    </div>
  </div>
</div>

app/views/stores/_bookmark_form.html.erb
<% if !Bookmark.exists?(user_id:user.id, store_name:name) %>
  <%= link_to bookmark_store_path(name), method: :post, class: 'btn_fav' do %>
    <i class="far fa-star"></i>
    <span>お気に入りに登録</span>
  <% end %>
<% else %>
  <%= link_to bookmark_store_path(name), method: :delete, class: 'btn_fav' do %>
    <i class="fas fa-star"></i>
    <span>お気に入りから解除</span>             
  <% end %>
<% end %>

app/views/stores/_list_store.html.erb
<% lists.each do |list| %>
<div class="col-md-3 list">
  <div class="box">
    <li class="liii">
      <div class="list-product">
        <p><%= list.product %></p>
      </div>
      <div class="list-amount-price">
        <span class="list-amount"><%= list.amount %><%= list.unit %></span>
        <span class="list-price"><%= list.price %>円</span>
      </div>
      <div class="list-date-user">
        <span><%= list.updated_at.to_s(:datetime_jp) %></span>
        <span>@<%= list.user.name %></span>
      </div>
    </li>
  </div>
</div>
<% end %> 

app/views/stores/_sort_order.html.erb
<select name="sort_order", class="sort_order">
  <option value="location.pathname", name="location.pathname">並び替え</option>
  <option value="price_asc">価格の安い順</option>
  <option value="price_desc">価格の高い順</option>
  <option value="created_at_asc">投稿の古い順</option>
  <option value="created_at_desc">投稿の新しい順</option>
  <option value="product">商品順</option>
</select>

app/views/stores/index.html.erb
<% content_for(:html_title) { '周辺のスーパー' } %>
<section class="stSection bgc">
  <div class="container">
    <div class="main-cont">
      <ul class="breadcrumbs left">
        <li>
          <p href="#">周辺のスーパー</p>
        </li>
      </ul>
      <div class="one-col">
        <div class="shop_search_result">
          <ul>
            <% @super.map do |s| %>
              <li class="border-bottom">
                <%= link_to s['name'], store_path(s['name']), method: :get %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/stores/show.html.erb
<% content_for(:html_title) { @name } %>
<section class="stSection">
  <div class="container">
    <div class="shop_header_inner">
      <div class="shop_information">
        <div class="inlineblock">
          <h2 class="title"><%= @name %></h2>
          <div class="favorite">
            <% if logged_in? %>
              <%= render 'bookmark_form', user: current_user, name: @name %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="shop_address">
        <% unless @super.nil? %>
          <p>住所：<%= @super['formatted_address'] %></p>
        <% end %>
      </div>
    </div>
    <div class="shop_add_lists">
      <% if logged_in? %>
        <%= render 'add_lists', list: @list, name: @name %>
      <% end %>
    </div>
  </div>
  <div class="main_shop_lists">
    <div class="shop_lists_title ml60">
      <p>買い物リスト</p>
      <div class="select-wrap cp_ipselect cp_sl01">
        <%= render 'sort_order' %>
      </div>
    </div>
    <div class="shop_lists">
      <div class="row">
      <% unless @lists.blank? %>
        <ul>
          <%= render 'list_store', lists: @lists %>
        </ul>
        <%= will_paginate @lists %>
      <% else %>
        <div>
          <p>まだリストはありません</p>
        </div>
      <% end %>
      </div>
    </div>
  </div>
  <div class="review">
    <div class="review_title">
      <p>口コミ</p>
      <div class="shop_add_review">
        <% if logged_in? %>
          <%= render 'add_review', review: @review, name: @name %>
        <% end %>  
      </div>
    </div>
    <div class="shop_lists2">
      <div class="row">
      <% unless @reviews.blank? %>
        <ul>
          <%= render @reviews %>
        </ul>
        <%= will_paginate @lists %>
      <% else %>
        <div>
          <p>まだ口コミはありません</p>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</section>