config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :stores, only: [:show, :index] do
    member do
      post 'bookmark' => 'bookmarks#create'
      delete 'bookmark' => 'bookmarks#destroy'
    end
  end
  resources :users do
    member do
      get :bookmarks
    end
  end
  resources :lists, only: [:create, :destroy]
  resources :reviews, only: [:create, :destroy]
  get    'signup'      =>  'users#new'
  post   'signup'      =>  'users#create'
  get    'login'       =>  'sessions#new'
  post   'login'       =>  'sessions#create'
  delete 'logout'      =>  'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_many :lists, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :bookmarks]
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update, :destroy]

  def show
    @list = List.new
    if params[:search]
      @lists = List.where(user_id: @user.id).search(params[:search]).defo(params[:page])
    else
      @lists = List.where(user_id: @user.id).latest_order.defo(params[:page])
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:info] = '登録が完了いたしました！'
      redirect_to root_url
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:success] = 'ユーザーを削除しました。'
    redirect_to root_path
  end

  def bookmarks
    @bookmarks = @user.bookmarks.all
    if params[:search]
      @lists = List.bookmarks(@bookmarks).search(params[:search]).defo(params[:page])
    else
      @lists = List.bookmarks(@bookmarks).latest_order.defo(params[:page])
    end
  end

  private

  def set_user
    @user = User.find_by(id: params[:id])
    redirect_to root_path if @user.nil?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/views/users/_add_lists.html.erb
<button type="button" class="btn_add_list" data-toggle="modal" data-target="#post">
<i class="fa fa-plus-circle"></i>買い物リストの追加</button>
<div class="modal fade" id="post" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog wid" role="document">
    <div class="modal-content">
      <%= form_with(model: list, local: true) do |f| %>
        <div class="modal-body pd15170">
          <ul class="modal-ul">
            <li>
              <%= f.label :product, '商品' %>
              <%= f.text_field :product %>
            </li>
            <li>
              <%= f.label :price, '金額' %>
              <%= f.text_field :price %>円              
            </li>
            <li>
              <%= f.label :amount, '数量' %>
              <%= f.text_field :amount %>
              <%= f.select :unit, [["個入り", "個入り"], ["本", "本"], ["パック", "パック"], ["袋", "袋"],["g(当り)", "g(当り)"],["切", "切"]], include_blank: "選択" %>
            </li>
            <li>
                <%= f.select :store_name, user.bookmarks.map { |b| [b.store_name, b.store_name] }, include_blank: "店名" %>
            </li>
          </ul>
        </div>
        <div class="modal-footer textcenter">
          <button type="button" class="btn circle-btn pl-10" data-dismiss="modal">閉じる</button>
          <%= f.submit "保存", class: "btn circle-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, url: signup_path, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h3>入力内容を確認して下さい。</h3>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :"名前" %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :"メールアドレス" %>
    <%= form.email_field :email %>
  </div>
  <div class="field">
    <%= form.label :"パスワード" %>
    <%= form.password_field :password %>
  </div>
  <div class="field">
    <%= form.label :"パスワード（確認）" %>
    <%= form.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= form.submit "作成", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_shop_lists.html.erb
<div class="user_lists">
  <% unless lists.blank? %>
  <ul>
    <% lists.each do |list| %>
      <li class="user_li">
        <div class="fw300">
          <span>@<%= list.user.name %></span>
          <span class="ml60"><%= list.updated_at.to_s(:datetime_jp) %></span>
        </div>
        <span class="user_list_store_name"><%= list.store_name %></span>
        <div class="right">
          <span class="user_list_product"><%= list.product %></span>
          <span class="user_list_amount"><%= list.amount %><%= list.unit %></span>
          <span class="user_list_price"><%= list.price %>円</span>
          <% if current_user?(list.user) %>
            <%= link_to '削除', "/lists/#{list.id}", method: :delete %>
          <% end %>
        </div>
      </li>
    <% end %> 
  </ul>
  <%= will_paginate lists %>
  <% else %>
    <div><p>まだリストはありません</p></div>
  <% end %>
</div>

app/views/users/bookmarks.html.erb
<% content_for(:html_title) { 'お気に入りのスーパー' } %>
<section class="stSection bgc">
  <div class="container">
    <div class="main-cont">
      <ul class="breadcrumbs left">
        <li>
          <p>お気に入りのスーパー</p>
        </li>
      </ul>
      <div class="one-col">
        <div class="shop_search_result">
          <ul>
            <% @bookmarks.each do |b| %>
              <li class="border-bottom">
                <%= link_to b.store_name, store_path(b.store_name), method: :get %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="main_user_lists">
      <div class="shop_lists_title">
        <p>買い物リスト</p>
          <div class="search-tag">
            <%= form_tag(bookmarks_user_path(@user),:method => 'get') do %>
              <%= text_field_tag :search, params[:search], :class =>'textbox', :placeholder =>"例(りんご/納豆etc...)" %>
            <% end %>
          </div>
      </div>
      <%= render 'shop_lists', lists: @lists %>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<% content_for(:html_title) { 'マイページ' } %>
<section class="stSection bgc user-p">
  <div class="wrapper">
    <div class="container">
      <div class="main_user">
        <div class="subject">
          <h1 class="user_title">
          ユーザー情報を変更する
          </h1>
          <div class="new_form_fields">
            <div class="user_form">
              <%= form_with(model: @user, local: true) do |form| %>
                <% if @user.errors.any? %>
                  <div id="error_explanation">
                    <h3>入力内容を確認して下さい。</h3>
                    <ul>
                    <% @user.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>
                <div class="field">
                  <%= form.label :"名前" %>
                  <%= form.text_field :name %>
                </div>
                <div class="field">
                  <%= form.label :"メールアドレス" %>
                  <%= form.email_field :email %>
                </div>
                <div class="field">
                  <%= form.label :"パスワード" %>
                  <%= form.password_field :password %>
                </div>
                <div class="field">
                  <%= form.label :"パスワード（確認）" %>
                  <%= form.password_field :password_confirmation %>
                </div>
                <div class="actions">
                  <%= form.submit "作成", class: "btn btn-primary" %>
                </div>
              <% end %>
            </div>
          </div>
          <%= link_to 'Back', @user %>
          <%= link_to 'delete', "/users/#{@user.id}", method: :delete, data: { confirm: '本当に削除しますか？' } %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/new.html.erb
<% content_for(:html_title) { '新規登録' } %>
<section class="stSection bgc user-p">
  <div class="wrapper">
    <div class="container">
      <div class="main_user">
        <div class="subject">
          <h1 class="user_title">
          ユーザー登録する
          </h1>
          <div class="new_form_fields">
            <div class="user_form">
              <%= render 'form', user: @user %>
            </div>
          </div>
          <%= link_to 'Back', "/" %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<% content_for(:html_title) { 'マイページ' } %>
<section class="stSection">
  <div class="container">
    <div class="shop_header_inner">
      <div class="shop_information">
        <div class="inlineblock">
          <h2 class="title"><%= @user.name %></h2>
          <div class="favorite">
            <% if logged_in? %>
              <%= link_to "編集", edit_user_path(@user) %>
            <% end %>
          </div>
        </div>   
      </div>
    </div>
    <div class="shop_add_lists">
      <%= render 'add_lists', user: @user, list: @list %>
    </div>
  </div>
  <div class="main_user_lists">
    <div class="shop_lists_title">
      <p>買い物リスト</p>
        <div class="search-tag">
          <%= form_tag(user_path(@user),:method => 'get') do %>
            <%= text_field_tag :search, params[:search], :class =>'textbox', :placeholder =>"例(りんご/納豆etc...)" %>
          <% end %>
        </div>
    </div>
    <%= render 'shop_lists', lists: @lists %>
  </div>
</section>