config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :stores, only: [:show, :index] do
    member do
      post 'bookmark' => 'bookmarks#create'
      delete 'bookmark' => 'bookmarks#destroy'
    end
  end
  resources :users do
    member do
      get :bookmarks
    end
  end
  resources :lists, only: [:create, :destroy]
  resources :reviews, only: [:create, :destroy]
  get    'signup'      =>  'users#new'
  post   'signup'      =>  'users#create'
  get    'login'       =>  'sessions#new'
  post   'login'       =>  'sessions#create'
  delete 'logout'      =>  'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <div class="footer-div">
      <p>©2020 Supermemo Inc.</p>
    </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="global_header">
  <div class="header_container">
    <div class="header_inner">
      <div class="bargains_header">
        <div class="f_left service_header_inner">
        <a href="/" class="service_logo f_left bargain_logo">スパメモ</a>
        </div>
        <div class="my_menu f_right">
          <ul>
            <li class="shop_search">
            <a href="/#search-super">
              <div class="icon_font icf-search">
              <i class="fa fa-search fa-3x"></i></div>
              <div class="label">スーパーを探す</div>
            </a>
            </li>
            <% if logged_in? %>
              <li class="togglable_link_wrapper subscribed_shops_menu off">
                <%= link_to bookmarks_user_path(current_user) do %>
                  <div class="icon_font icf_fav">
                  <i class="fa fa-store-alt fa-3x"></i></div>
                  <div class="label">お気に入り</div>
                <% end %>
              </li>
              <li class="mypage">
                <%= link_to current_user do %>
                  <div class="icon_font icf-mypage">
                  <i class="fa fa-home fa-4x"></i></div>
                  <div class="label">マイページ</div>
                <% end %>
              </li>
              <li class="last togglable_link_wrapper user_icon_wrapper off">
                <button class="button small login_button">
                  <%= link_to "ログアウト", logout_path, method: :delete %>
                </button>
              </li>
            <% else %>
              <li class="last togglable_link_wrapper user_icon_wrapper off">
                <button class="button small login_button">
                  <%= link_to "ログイン", login_path %>
                </button>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:html_title) ? yield(:html_title) : "Default" %></title>
    <meta charset="utf-8">  
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">  
    <title>AppName</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- CUSTOM CSS -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->    
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container"></div>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>